default: &default
  adapter: mysql2
  database: <%= ENV["MYSQL_DATABASE"] || 'nuuvem_teste' %>
  username: <%= ENV["MYSQL_ROOT_NAME"] || 'root' %>
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] || 'root' %>
  port: <%= ENV["MYSQL_DB_PORT"] || 3306 %>
  host: <%= ENV["MYSQL_DB_HOST"] || '127.0.0.1' %>
  timeout: 5000

development:
  <<: *default
  database: nuuvem_teste_development

test: &test
  <<: *default
  database: nuuvem_teste_test

production:
  <<: *default
  database: nuuvem_teste_production

